JWT auth
artux-net/ailingo-server pull request #10
Opened 2024-11-20 22:16 UTC by VangelNum

2024-11-23 09:43 UTC, prygunov requested changes

2024-11-23 09:43 UTC, prygunov commented on .github/workflows/test.yml
> +        run: ./gradlew test --stacktrace --info
оставь только --stacktrace, на будущее

2024-11-23 09:43 UTC, prygunov commented on build.gradle.kts
> +    implementation("me.paulschwarz:spring-dotenv:4.0.0")
если эта тема не нужна и не работает лучше убрать, чтоб не плодить зависимости

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/configuration/AuthConfig.java
> +    public AuthenticationProvider authenticationProvider() {
проверь, кажется часть бинов отсюда уже есть в контексте и конфигурация на это дело не нужна

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/configuration/SwaggerConfig.java
> -@SecurityScheme(
го оставим пока

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/configuration/security/SecurityConfiguration.kt
> +            .sessionManagement { it.sessionCreationPolicy(SessionCreationPolicy.STATELESS) }
а почему?

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/entity/RefreshTokenEntity.java
> +@Getter
го сделаем с редисом, на будущее будет полезнее - описать его в докер композе да и тут логин пароль прокинуть

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/entity/user/UserEntity.java
> +    public boolean isAccountNonExpired() {
раз на то пошло можно соответствующие поля добавить

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/model/ApiResponse.kt
> +    val message: String,
эти три поля можно объединить в одно - статус, наверное будет енамом

2024-11-23 09:43 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/model/register/RegisterResponse.kt
> +    val userDto: UserDto
поле лучше без dto называть, просто user будет достаточно

2024-11-23 09:48 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/configuration/security/JwtUtil.kt
> +    @Value("\${jwt.refresh-token.expiration}") private val refreshTokenExpiration: Long
можно класс пропертей сделать, @ConfigurationProperties или как-то так, там префикс задать - jwt

2024-11-23 10:13 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/configuration/security/JwtUtil.kt
> +    @Value("\${jwt.refresh-token.expiration}") private val refreshTokenExpiration: Long
У тебя там класс отдельный есть ValuesService, могу туда все закинуть
https://github.com/artux-net/ailingo-server/blob/917bc2f986f046f9fa6d11b4964c3be6d3c191de/src/main/kotlin/net/artux/ailingo/server/service/impl/ValuesService.java#L15

2024-12-10 16:07 UTC, prygunov approved these changes

2024-12-10 16:28 UTC, VangelNum commented on .github/workflows/test.yml
> +        run: ./gradlew test --stacktrace --info
оставил

2024-12-10 16:28 UTC, VangelNum commented on build.gradle.kts
> +    implementation("me.paulschwarz:spring-dotenv:4.0.0")
не работает

2024-12-10 16:28 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/configuration/AuthConfig.java
> +    public AuthenticationProvider authenticationProvider() {
не нужна

2024-12-10 16:28 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/configuration/SwaggerConfig.java
> -@SecurityScheme(
оставил

2024-12-10 16:28 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/configuration/security/SecurityConfiguration.kt
> +            .sessionManagement { it.sessionCreationPolicy(SessionCreationPolicy.STATELESS) }
важно

2024-12-10 16:28 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/entity/RefreshTokenEntity.java
> +@Getter
сделал

2024-12-10 16:28 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/entity/user/UserEntity.java
> +    public boolean isAccountNonExpired() {
добавил

2024-12-10 16:28 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/model/ApiResponse.kt
> +    val message: String,
сделал

2024-12-10 16:29 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/model/register/RegisterResponse.kt
> +    val userDto: UserDto
сделал

2024-12-10 16:29 UTC, VangelNum commented on src/main/kotlin/net/artux/ailingo/server/configuration/security/JwtUtil.kt
> +    @Value("\${jwt.refresh-token.expiration}") private val refreshTokenExpiration: Long
сделал

2024-12-10 16:32 UTC, Artemka228not approved these changes

2024-12-10 16:46 UTC, merged