user streak
artux-net/ailingo-server pull request #5
Opened 2024-11-05 11:47 UTC by Artemka228not

2024-11-07 11:27 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/service/user/UserServiceImpl.java
> +        }else currentUser.setStreak(currentUser.getStreak() + 1);
Закрывать чужой тред плохо, тем более ты его не пофиксил

2024-11-17 08:12 UTC, prygunov requested changes

2024-11-17 08:12 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/service/user/UserServiceImpl.java
> +            if (currentUser.getLastStrikeAt().isBefore(yesterday)) {
форматирование, у тебя уехал if

2024-11-17 08:12 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/service/user/UserServiceImpl.java
> +                if (currentUser.getLastStrikeAt().truncatedTo(ChronoUnit.DAYS)!=Instant.now().truncatedTo(ChronoUnit.DAYS)) {
currentUser.getLastStrikeAt().truncatedTo(ChronoUnit.DAYS) нужно вынести в отдельную переменную

2024-11-17 08:12 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/service/user/UserServiceImpl.java
> +                if (currentUser.getLastStrikeAt().truncatedTo(ChronoUnit.DAYS)!=Instant.now().truncatedTo(ChronoUnit.DAYS)) {
Instant.now().truncatedTo(ChronoUnit.DAYS) тоже

2024-11-17 08:12 UTC, prygunov commented on src/main/kotlin/net/artux/ailingo/server/service/user/UserServiceImpl.java
> +        Instant yesterday = Instant.now().minus(1, ChronoUnit.DAYS).truncatedTo(ChronoUnit.DAYS);
все что дальше нужно вынести в отдельный метод

2024-11-19 19:21 UTC, prygunov approved these changes

2024-11-23 15:52 UTC, VangelNum approved these changes

2024-11-23 15:55 UTC, merged